# Two dimension

In [1]:
import numpy as np

In [2]:
num_array01 = np.array([[1,2,3],
                       [4,5,6],
                       [7,8,9]]) # Двумерные массивы  

In [3]:
print(num_array01)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
print(num_array01[2,2]) # Обращаемся к строке - 2 и столбцу 2, строки по горизонтали, 
# столбцы по вертикали. 

9


In [5]:
num_array01.shape  # Атрибу показывает размер по оси, по горизонтали и по вертикали 

(3, 3)

In [35]:
num_array01.ndim # Атрибут показывает число измерений

2

In [36]:
num_array01.dtype # Атрибут показывает тип данных внутри массива

dtype('int64')

In [37]:
num_array01.itemsize # Показывае тразмер одного элемента в байтах

8

In [38]:
second = np.array([[4,5,3],[10,43,2], [2,34,45]])

In [39]:
print(second)

[[ 4  5  3]
 [10 43  2]
 [ 2 34 45]]


In [40]:
second.shape   

(3, 3)

In [41]:
num_array01 + second # Сложение двух массивов, главное размер оси должен совпадать у обоих массивов 

array([[ 5,  7,  6],
       [14, 48,  8],
       [ 9, 42, 54]])

In [42]:
second + 1 # Каждому из элементов массива добавили единицу при этом оргинальный массив не поменялся

array([[ 5,  6,  4],
       [11, 44,  3],
       [ 3, 35, 46]])

In [43]:
second - 1 # Отнимаем из каждого элемента единицу при этом оргинальный массив не поменялся

array([[ 3,  4,  2],
       [ 9, 42,  1],
       [ 1, 33, 44]])

In [44]:
second * 2 # Умножаем каждый элемент на два при этом оргинальный массив не поменялся

array([[ 8, 10,  6],
       [20, 86,  4],
       [ 4, 68, 90]])

In [45]:
second / 2 # Делим каждый элемент массива на два  при этом оргинальный массив не поменялся

array([[ 2. ,  2.5,  1.5],
       [ 5. , 21.5,  1. ],
       [ 1. , 17. , 22.5]])

In [47]:
second[1,1] # Вызываем элемент который по оси 0 имет индекс 1, и по оси 1 имеет индекс 1

np.int64(43)

In [51]:
np.concatenate((num_array01, second)) # Слияние 2 массивов с одинаковой 
# размерностью с помощю метода .concatenate по оси 0(ось 0 стоит по умолчанию) , 
# порядок следования массивов имеет роль.с по оси 1(нужно указат axis=1) 

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 4,  5,  3],
       [10, 43,  2],
       [ 2, 34, 45]])

In [52]:
np.concatenate((num_array01, second), axis=1) # Слияние 2 массивов с одинаковой 
# размерностью с помощю метода .concatenate по оси 1(нужно указат axis=1) ,
# порядок следования массивов имеет роль. Такое соединение, соединяет по горизонтали 

array([[ 1,  2,  3,  4,  5,  3],
       [ 4,  5,  6, 10, 43,  2],
       [ 7,  8,  9,  2, 34, 45]])

# An array with  mixed data types

In [9]:
str_array = np.array([True, 10, 'abc', 5.5])

In [10]:
print(str_array)

['True' '10' 'abc' '5.5']


In [11]:
str_array.dtype

dtype('<U32')

In [12]:
str_array.dtype.name

'str1024'

In [13]:
str_array.itemsize

128

In [14]:
obj_array = np.array([{'city': 'London'},{'city': 'Boston'}])

In [15]:
print(obj_array)

[{'city': 'London'} {'city': 'Boston'}]


In [16]:
obj_array.dtype.name

'object'

In [17]:
obj_array.itemsize

8