# Создание массиво с помощю функций

In [1]:
import numpy as np

In [2]:
np.zeros((3,4,2))  #  .zeros() это функция NumPy, которая создаёт массив, заполненный нулями, 
# по умолчанию float

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [9]:
np.zeros((3,4),dtype=int) # Создаём массив 2 мерный с 3 строками и 4 колонками, типа int

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [11]:
np.ones((5,3),dtype=int) # это функция NumPy, которая создаёт массив, заполненный единицами.

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [5]:
np.random.random((2,4)) # Создай массив из рандомных чисел
# np	NumPy	модуль (пакет)
# np.random	подмодуль внутри NumPy	модуль
# np.random.random	функция внутри подмодуля	функция
# Диапазон: каждое число от 0.0 до 1.0 (не включая 1.0)

array([[0.16302432, 0.07136678, 0.46419246, 0.16680297],
       [0.46764608, 0.43839558, 0.13325401, 0.22800784]])

In [37]:
np.random.seed(10)   # ed — это функция модуля NumPy, 
# Которая задаёт стартовое число (seed) для генератора псевдослучайных чисел.
np.random.random((2,4)) # Создай массив из рандомных чисел которые начинаются с .seed(10)
# np	NumPy	модуль (пакет)
# np.random	подмодуль внутри NumPy	модуль
# np.random.random	функция внутри подмодуля	функция
# Диапазон: каждое число от 0.0 до 1.0 (не включая 1.0)

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388],
       [0.49850701, 0.22479665, 0.19806286, 0.76053071]])

In [38]:
np.random.seed(15)
np.random.randint(10,20, size=(2,4)) # В начале укказываем чсило с которого 
# Необходиомо выбирать случайные числа 
# Потом указываем до какой границы брать числа
# Далее указываем какой массив создать 

array([[18, 15, 15, 17],
       [10, 17, 15, 16]], dtype=int32)

In [39]:
np.random.seed(10)
np.random.uniform(1, 10, size=(2,4)) # "Эта фуцкнция работате как random но здесь можнo указать диапазон, 
# данные будут по типу float  

array([[7.94188579, 1.18676754, 6.70283411, 7.73923494],
       [5.48656311, 3.02316981, 2.78256578, 7.84477641]])

In [40]:
np.random.choice(np.array([1,2,3]), size=20) 

array([1, 3, 1, 3, 1, 1, 1, 3, 1, 3, 3, 2, 1, 1, 3, 2, 3, 2, 2, 2])