In [1]:
import numpy as np               # Ипортрируем модуль и называем np 

In [2]:
num_array = np.array([1,2,3,4,5]) # Массив numpy, это не список из python 
print(num_array)

[1 2 3 4 5]


In [3]:
type(num_array)      # Тип Класс

numpy.ndarray

In [4]:
print(num_array[1])  # Достаём первый индекс из массива numpy

2


In [5]:
num_array.shape

(5,)

In [6]:
num_array.ndim

1

In [7]:
num_array.dtype

dtype('int64')

In [8]:
num_array.itemsize

8

In [14]:
sec_num = np.array([1,3,4,6,4])  # создаём второй одномерный массив 

In [15]:
print(sec_num)

[1 3 4 6 4]


In [16]:
np.concatenate((num_array, sec_num)) # Соединение одномерного массива

array([1, 2, 3, 4, 5, 1, 3, 4, 6, 4])