# Функция arange()  — это функция модуля NumPy, которая создаёт массив с последовательностью чисел в заданном диапазоне с заданным шагом.

In [1]:
import numpy as np

In [2]:
np.arange(10) # Создаём упорядоченый одномерный массив numpy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(15,25) # Создаём упорядоченый одномерный массив numpy от одного  значения до дургово

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [4]:
np.arange(10,25, 5) # Создаём упорядоченый одномерный массив numpy от одного  значения до другово 
# c определёным шагом 5

array([10, 15, 20])

In [5]:
np.arange(-10, 30, 2) # Создаём упорядоченый одномерный массив numpy от одного  значения до другово 
# c определёным шагом 2

array([-10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8,  10,  12,  14,
        16,  18,  20,  22,  24,  26,  28])

# Функция reshape() — это метод массива NumPy, который меняет форму массива, не меняя сами данные.

In [6]:
np.arange(20).reshape([2,10]) # Из массива с 20 элеменатми создаём двумерный массив

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [7]:
np.arange(20).reshape([4,5]) # в reshape указываем форму массива 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [8]:
np.arange(20).reshape([4,5]).reshape([2,2,5]).reshape([4,5]) # Reshape всего лишь меняет форму массива
# Но можно также менять форму в большую мерность и меньшую мерность, всё в одной строке.  

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [9]:
np.random.random((10,)).reshape([2,5])

array([[0.66837745, 0.56028736, 0.0131262 , 0.9397166 , 0.73394326],
       [0.44382034, 0.02469567, 0.57533837, 0.98728732, 0.16961463]])

In [10]:
np.random.seed(10)
np.random.random((4,10)).reshape([2,20]) 

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
        0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981,
        0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096,
        0.61252607, 0.72175532, 0.29187607, 0.91777412, 0.71457578],
       [0.54254437, 0.14217005, 0.37334076, 0.67413362, 0.44183317,
        0.43401399, 0.61776698, 0.51313824, 0.65039718, 0.60103895,
        0.8052232 , 0.52164715, 0.90864888, 0.31923609, 0.09045935,
        0.30070006, 0.11398436, 0.82868133, 0.04689632, 0.62628715]])

# Flaten - это метод массива NumPy, который превращает многомерный массив в одномерный, копируя данные.

In [11]:
np.random.seed(10)
np.random.randint(10, 80, (4,3,3))

array([[[19, 25, 74],
        [38, 39, 18],
        [10, 50, 46]],

       [[26, 21, 64],
        [72, 43, 59],
        [61, 64, 79]],

       [[23, 35, 23],
        [40, 40, 22],
        [75, 41, 67]],

       [[46, 37, 28],
        [32, 33, 21],
        [38, 19, 25]]], dtype=int32)

In [12]:
np.random.seed(10)
np.random.randint(10, 80, (4,3,3)).flatten() # Меняем трёх мерный массив в одномерный 

array([19, 25, 74, 38, 39, 18, 10, 50, 46, 26, 21, 64, 72, 43, 59, 61, 64,
       79, 23, 35, 23, 40, 40, 22, 75, 41, 67, 46, 37, 28, 32, 33, 21, 38,
       19, 25], dtype=int32)