In [1]:
import numpy as np

## 1. Calculating Total Revenue

In [2]:
prices = np.array([19.99,29.99,14.99,9.99,24.99]) # Цены товаров (колонка цен)

In [3]:
print(prices)

[19.99 29.99 14.99  9.99 24.99]


In [4]:
quan = np.array([10,5,8,12,3]) # Кол-во товаров (колонка цен)

In [5]:
print(quan)

[10  5  8 12  3]


In [6]:
revenue = prices * quan # Цена умноженая на кол-во (доход по каждому из товаров)

In [7]:
print(revenue) 

[199.9  149.95 119.92 119.88  74.97]


In [8]:
total_rev = np.sum(revenue)

In [9]:
print(total_rev) # Общая сумма выручки

664.62


## 2.Analyzing Blog Post Stat

In [10]:
views = np.array([100,500, 800, 1200,600])

In [11]:
print(views)                                                                                                          

[ 100  500  800 1200  600]


In [12]:
max_views = np.max(views) # Максимальная сумма
print(max_views)

1200


In [13]:
min_views = np.min(views) # Минимальная сумма
print(min_views)

100


In [14]:
np.random.seed(10)
a = np.random.randint(1, 100, (3,3)) # Создаём двумерный массив, 
# который будет состоять только из числе от 1 до 100
print(a)

[[10 16 65]
 [29 90 94]
 [30  9 74]]


In [15]:
print(np.max(a)) # Находим самую большую цифру в двумерном массиве

94


In [16]:
ave_views = np.mean(views) # Находим среднюю  массива views
print(ave_views)           

640.0


In [17]:
ave_a = np.mean(a) # Счиатем среднюю массива a
print(ave_a)

46.333333333333336


In [18]:
ave_a = np.round(np.mean(a))
print(ave_a) # округляем среднюю 

46.0


In [19]:
total_viw = np.sum(views)
print(total_viw) # Находим сумму по колонке 

3200


In [20]:
median = (len(views) + 1) // 2 # Индекс под которым находится медианая 
print(median)

3


In [21]:
median01 = np.median(views) # Находим медианную через непосредсвенно функцию 
print(median01)

600.0


## 3. Splitting Order into Batches

In [22]:
order_ids = np.array([1001, 1002, 1003,1004, 1005, 1006, 1007, 1008, 1009,1010,1011,1012])
print(order_ids)

[1001 1002 1003 1004 1005 1006 1007 1008 1009 1010 1011 1012]


In [23]:
batchas = np.split(order_ids, 4) # Разделяем на батчи, 
# указываем конкрктено на сколько батчей разделить 
print(batchas)

[array([1001, 1002, 1003]), array([1004, 1005, 1006]), array([1007, 1008, 1009]), array([1010, 1011, 1012])]


In [24]:
for bath in batchas:
    print(bath)

[1001 1002 1003]
[1004 1005 1006]
[1007 1008 1009]
[1010 1011 1012]


In [25]:
for bath in batchas: # берём элемент по индексу 0 
    print(bath[0])

1001
1004
1007
1010


In [26]:
for i, bath in enumerate(batchas):
    print(f'Batch number {i}:')
    print('First element in the batch:', bath[0])
    print('Second element in the bath:', bath[1])

Batch number 0:
First element in the batch: 1001
Second element in the bath: 1002
Batch number 1:
First element in the batch: 1004
Second element in the bath: 1005
Batch number 2:
First element in the batch: 1007
Second element in the bath: 1008
Batch number 3:
First element in the batch: 1010
Second element in the bath: 1011


## 4. Categorizing Product Rating

In [27]:
ratings = np.array([4.5,3.2,2.8,5.0,4.1,3.9,2.5,4.7])
print(ratings)

[4.5 3.2 2.8 5.  4.1 3.9 2.5 4.7]


In [28]:
positiv_ratings = ratings[ratings >= 4.0] # Используя квадратные скобки мы можем 
# отфильтровать объекты в массиве numpy.
# Здесь находим позитивные отзывы
print(positiv_ratings)

[4.5 5.  4.1 4.7]


In [29]:
negative_ratings = ratings[ratings <= 4.0]
# Здесь находим негативные отзывы
print(negative_ratings)

[3.2 2.8 3.9 2.5]


## 5. Calculate Total and Average quantites sold

In [30]:
order_quant = np.array([[5,3,2,7],[10,6,3,9]]) # Создаём двумерный массив, каждая колонка это заказ с каким то кол-вом элементов.
print(order_quant)

[[ 5  3  2  7]
 [10  6  3  9]]


In [31]:
len01 = len(order_quant) # Кол-во заказов
print(len01)

2


In [32]:
total_quan_sold = order_quant.sum() # В этом случаи мы используем модуль 
print(total_quan_sold)

45


In [33]:
total_quan_sold = np.sum(order_quant) # В этом случаи используем функцию
print(total_quan_sold)

45


In [34]:
total_quan_sold = np.sum(order_quant, axis=0) # В этом случаи используем функцию и указываем ось по котрой проводить суммирование 
print(total_quan_sold)

[15  9  5 16]


In [35]:
total_quan_sold = np.sum(order_quant, axis=1) # В этом случаи используем функцию и указываем ось 
# по котрой проводить суммирование 
print(total_quan_sold) 

[17 28]


In [36]:
avg_quant_sold = np.mean(order_quant, axis=0) # Среднее товаров 

In [37]:
avg_quant_sold = np.mean(order_quant, axis=1) # Среднее заказов 
print(avg_quant_sold)

[4.25 7.  ]


In [38]:
 order_quant.flatten()   # из двумерного массива сделали одномерный

array([ 5,  3,  2,  7, 10,  6,  3,  9])

## 6. Calculate Avarage product Rating and Maximum per Category

In [39]:
product_ratings = np.array([
    [4.3,4.2,2.6,1.4],
    [4.2,3.4,5.6,2],
    [1.3,2.6,3.5,4]])
print(product_ratings) # Каждая строка это отдельный товар, по горизонтали у нкас реётинг товара, 
# так как товара у нас 3 значит и среднюю мы будем считать по товарам 

[[4.3 4.2 2.6 1.4]
 [4.2 3.4 5.6 2. ]
 [1.3 2.6 3.5 4. ]]


In [41]:
avarage_rating_per_category = np.mean(product_ratings, axis=0) # Усредняем по колонке из axis=0
print(avarage_rating_per_category)

[3.26666667 3.4        3.9        2.46666667]


In [ ]:
avarage_rating_per_product = np.mean(product_ratings, axis=1) # Усредняем по строке из axis=1
print(avarage_rating_per_product )

In [45]:
max_rating_per_category = np.max(product_ratings, axis=0) # Максимальный рейтинг по категории 

In [46]:
min_rating_per_products = np.max(product_ratings, axis=1)# Максимальный рейтинг по продукту
print(min_rating_per_products)

[4.3 5.6 4. ]


## 7 Generation of the sample stock data

In [1]:
# Создаём данные 
# Из этих данных будет создан массив
companies = ['Google', 'Microsoft', 'Apple'] 
days = ['Mon 1 April', 'Thu 2 April']
price_types = ['Open', 'Close', 'High', 'Low']

In [52]:
np.random.seed(1) # Задаём стартовое число для генератора случайных цифр
# Далее у нас создаются случайные даные 
#  Ось 0 — это «слои» (глубина), по одному на каждую компанию.
#  Ось 1 — это строки, по одной на каждый день.
#  Ось 2 — это столбцы, по одному на каждый тип цены.
stock_prices = np.round(np.random.random((len(companies), len(days), len(price_types))), 3)
# np.random.random(shape) ждёт числа (или кортеж чисел) — размеры будущего массива.
# len(companies) = 3, len(days) = 2, len(price_types) = 4 — это числа, которые random() и ждёт.
# Получаем кортеж (3, 2, 4), и random() создаёт массив этой формы со случайными числами.
print(stock_prices)

[[[0.417 0.72  0.    0.302]
  [0.147 0.092 0.186 0.346]]

 [[0.397 0.539 0.419 0.685]
  [0.204 0.878 0.027 0.67 ]]

 [[0.417 0.559 0.14  0.198]
  [0.801 0.968 0.313 0.692]]]


In [53]:
stock_prices.shape # Форма нашего массива

(3, 2, 4)

In [56]:
for i, company in enumerate(companies):
    print(f'Stock prices for the {company}:')
    for j, day in enumerate(days):
        print(f'Day:{day}')
        for k, price_type in enumerate(price_types):
            print(f'{price_type} Price: {stock_prices[i,j,k]}')
        print('')
    print('')
    

Stock prices for the Google:
Day:Mon 1 April
Open Price: 0.417
Close Price: 0.72
High Price: 0.0
Low Price: 0.302

Day:Thu 2 April
Open Price: 0.147
Close Price: 0.092
High Price: 0.186
Low Price: 0.346


Stock prices for the Microsoft:
Day:Mon 1 April
Open Price: 0.397
Close Price: 0.539
High Price: 0.419
Low Price: 0.685

Day:Thu 2 April
Open Price: 0.204
Close Price: 0.878
High Price: 0.027
Low Price: 0.67


Stock prices for the Apple:
Day:Mon 1 April
Open Price: 0.417
Close Price: 0.559
High Price: 0.14
Low Price: 0.198

Day:Thu 2 April
Open Price: 0.801
Close Price: 0.968
High Price: 0.313
Low Price: 0.692


